temporarily_disable:
  target:
    entity:
      domain: datetime
      integration: motion_dimmer
  fields:
    seconds:
      example: 120
      selector:
        number:
          min: 1
          max: 43200
          mode: box
          unit_of_measurement: Seconds
    minutes:
      example: 120
      selector:
        number:
          min: 1
          max: 720
          mode: box
          unit_of_measurement: Minutes
    hours:
      example: 12
      selector:
        number:
          min: 1
          max: 12
          mode: box
          unit_of_measurement: Hours
enable:
  target:
    entity:
      domain: switch
      integration: motion_dimmer
finish_timer:
  target:
    entity:
      domain: sensor
      integration: motion_dimmer
